---
- hosts: localhost

  tasks:
  - name: Add Openshift Containers Provider to ManageIQ
    manageiq:
      name: '{{ name }}'
      type: '{{ type }}'
      url: '{{ url }}'
      username: '{{ username }}'
      password: '{{ password }}'
      hostname: '{{ hostname }}'
      port: '{{ port }}'
      token: '{{ token }}'
      metrics: '{{ metrics | default(omit) }}'
      hawkular_hostname: '{{ hawkular_hostname | default(omit) }}'
      hawkular_port: '{{ hawkular_port | default(omit) }}'
    register: result

  - debug: var=result
